# Generated by Django 4.2.3 on 2023-07-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotation_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='item_bought',
            field=models.JSONField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='order_count',
            field=models.JSONField(),
        ),
    ]
