# Generated by Django 4.2.3 on 2023-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_alter_quotation_item_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='item_orders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='item_bought',
            field=models.JSONField(),
        ),
    ]
