# Generated by Django 4.2.3 on 2023-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_remove_quotation_item_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='item_bought',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='order_count',
            field=models.JSONField(default=dict),
        ),
    ]
